apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  labels:
    app: gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops
  template:
    metadata:
      labels:
        app: gitops
    spec:
      containers:
      - name: gitops-container
        image: gitops-demo:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
