apiVersion: apps/v1
kind: Deployment
metadata:
name: gitops-app
spec:
replicas: 2
selector:
matchLabels:
app: gitops
template:
metadata:
labels:
app: gitops
spec:
containers:
- name: app
image: gitops-demo:v1
ports:
- containerPort: 5000
